# Generated by Django 2.2.6 on 2023-01-07 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostForm',
        ),
    ]
